/*
 * Copyright (c) 2015 Red Hat, Inc.
 * Copyright (c) 2015 Nathaniel McCallum <npmccallum@redhat.com>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in
 *       the documentation and/or other materials provided with the
 *       distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
 * IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "asn1.h"

#include <errno.h>
#include <stdbool.h>

/*
 * Kerberos
 */
ASN1_SEQUENCE(KRB5_ENCRYPTED_DATA) = {
    ASN1_EXP(KRB5_ENCRYPTED_DATA, etype, ASN1_INTEGER, 0),
    ASN1_EXP_OPT(KRB5_ENCRYPTED_DATA, kvno, ASN1_INTEGER, 1),
    ASN1_EXP(KRB5_ENCRYPTED_DATA, cipher, ASN1_OCTET_STRING, 2),
} ASN1_SEQUENCE_END(KRB5_ENCRYPTED_DATA)

IMPLEMENT_ASN1_FUNCTIONS(KRB5_ENCRYPTED_DATA)


/*
 * PAKE
 */
ASN1_SEQUENCE(PAKE_SUPPORT) = {
    ASN1_SIMPLE(PAKE_SUPPORT, etype, ASN1_INTEGER),
    ASN1_SEQUENCE_OF(PAKE_SUPPORT, groups, ASN1_OBJECT),
    ASN1_SEQUENCE_OF(PAKE_SUPPORT, hashes, ASN1_OBJECT),
} ASN1_SEQUENCE_END(PAKE_SUPPORT)

ASN1_SEQUENCE(PAKE_INFO) = {
    ASN1_SEQUENCE_OF(PAKE_INFO, ptypes, ASN1_INTEGER),
    ASN1_SEQUENCE_OF(PAKE_INFO, supports, PAKE_SUPPORT),
} ASN1_SEQUENCE_END(PAKE_INFO)

ASN1_SEQUENCE(PAKE_DATA) = {
    ASN1_SIMPLE(PAKE_DATA, ptype, ASN1_INTEGER),
    ASN1_SIMPLE(PAKE_DATA, etype, ASN1_INTEGER),
    ASN1_SIMPLE(PAKE_DATA, group, ASN1_OBJECT),
    ASN1_SIMPLE(PAKE_DATA, hash, ASN1_OBJECT),
    ASN1_SIMPLE(PAKE_DATA, data, ASN1_OCTET_STRING),
} ASN1_SEQUENCE_END(PAKE_DATA)

ASN1_CHOICE(PAKE_MESSAGE) = {
    ASN1_EXP(PAKE_MESSAGE, value.info, PAKE_INFO, PAKE_MESSAGE_TYPE_INFO),
    ASN1_EXP(PAKE_MESSAGE, value.data, PAKE_DATA, PAKE_MESSAGE_TYPE_EXCHANGE),
    ASN1_EXP(PAKE_MESSAGE, value.data, PAKE_DATA, PAKE_MESSAGE_TYPE_VERIFIER),
} ASN1_CHOICE_END(PAKE_MESSAGE)

IMPLEMENT_ASN1_FUNCTIONS(PAKE_SUPPORT)
IMPLEMENT_ASN1_FUNCTIONS(PAKE_INFO)
IMPLEMENT_ASN1_FUNCTIONS(PAKE_DATA)
IMPLEMENT_ASN1_FUNCTIONS(PAKE_MESSAGE)


/*
 * JPAKE
 */
ASN1_SEQUENCE(JPAKE_KEY) = {
    ASN1_SIMPLE(JPAKE_KEY, gv, ASN1_OCTET_STRING),
    ASN1_SIMPLE(JPAKE_KEY, r, ASN1_OCTET_STRING),
    ASN1_SIMPLE(JPAKE_KEY, x, ASN1_OCTET_STRING),
} ASN1_SEQUENCE_END(JPAKE_KEY)

ASN1_SEQUENCE(JPAKE_STEP1) = {
    ASN1_SIMPLE(JPAKE_STEP1, x1, JPAKE_KEY),
    ASN1_SIMPLE(JPAKE_STEP1, x2, JPAKE_KEY),
} ASN1_SEQUENCE_END(JPAKE_STEP1)

ASN1_CHOICE(JPAKE_MESSAGE) = {
    ASN1_EXP(JPAKE_MESSAGE, value.step1, JPAKE_STEP1, JPAKE_MESSAGE_TYPE_STEP1),
    ASN1_EXP(JPAKE_MESSAGE, value.step2, JPAKE_KEY, JPAKE_MESSAGE_TYPE_STEP2),
} ASN1_CHOICE_END(JPAKE_MESSAGE)

IMPLEMENT_ASN1_FUNCTIONS(JPAKE_KEY)
IMPLEMENT_ASN1_FUNCTIONS(JPAKE_STEP1)
IMPLEMENT_ASN1_FUNCTIONS(JPAKE_MESSAGE)
